from enum import Enum

class Tipo(Enum):
    AVISO=1
    BUQUE=2
    CORBETA=3
    DESTRUCTOR=4
    FRAGATA=5, 
    BUQUE_LOGISTICO=6
    LANCHA=7
    BUQUE_MULTIPROPOSITO=8
    PATRULLERO=9
    REMOLCADOR=10
    ROMPEHIELOS=11
    SUBMARINO=12 
    TRANSPORTE=13